// GENERATED by scripts/import-contributors.mjs — do not edit by hand.
// Source: github.com/stackshy/cloudemu contributors. Re-run the script to refresh.

export interface Contributor {
  login: string;
  avatar: string;
  contributions: number;
  url: string;
}

export const CONTRIBUTORS: Contributor[] = [
  {
    "login": "NitinKumar004",
    "avatar": "https://avatars.githubusercontent.com/u/215663108?v=4",
    "contributions": 504,
    "url": "https://github.com/NitinKumar004"
  },
  {
    "login": "thzgajendra",
    "avatar": "https://avatars.githubusercontent.com/u/219787351?v=4",
    "contributions": 136,
    "url": "https://github.com/thzgajendra"
  },
  {
    "login": "devansh-ar",
    "avatar": "https://avatars.githubusercontent.com/u/215661982?v=4",
    "contributions": 7,
    "url": "https://github.com/devansh-ar"
  },
  {
    "login": "arunesh-j",
    "avatar": "https://avatars.githubusercontent.com/u/176659112?v=4",
    "contributions": 5,
    "url": "https://github.com/arunesh-j"
  },
  {
    "login": "Satyam-Trivedi-ZS",
    "avatar": "https://avatars.githubusercontent.com/u/174587133?v=4",
    "contributions": 3,
    "url": "https://github.com/Satyam-Trivedi-ZS"
  },
  {
    "login": "GURSEWAK13",
    "avatar": "https://avatars.githubusercontent.com/u/122093332?v=4",
    "contributions": 2,
    "url": "https://github.com/GURSEWAK13"
  },
  {
    "login": "Gursewakzopdev",
    "avatar": "https://avatars.githubusercontent.com/u/215660967?v=4",
    "contributions": 2,
    "url": "https://github.com/Gursewakzopdev"
  },
  {
    "login": "aryanmehrotra",
    "avatar": "https://avatars.githubusercontent.com/u/44036979?v=4",
    "contributions": 1,
    "url": "https://github.com/aryanmehrotra"
  }
];

export const TOTAL_CONTRIBUTIONS = 660;
